name: Code review

on:
  workflow_dispatch: # Manual (for debug)
  pull_request:

jobs:
  code-review:
    name: Code review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Code review action
        id: test-action
        uses: getvictor/code-review-demo@main # Your action goes here
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
