name: Code review

on:
  workflow_dispatch: # Manual (for debug)
  # Running on PR without any reviews should fail
  pull_request:
  # Running on PR with the proper approving reviewer should pass
  pull_request_review:

defaults:
  run:
    shell: bash

permissions:
  # read contents of repo; all other permissions default to `none`
  contents: read

# This allows a subsequently queued workflow run to interrupt/cancel previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id}}
  cancel-in-progress: true

env:
  PR_NUMBER: ${{ github.event.number || github.event.pull_request.number }}

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Code review action
        id: test-action
        uses: getvictor/code-review@latest
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
