name: PR review

on:
  workflow_dispatch: # Manual (for debug)
  # Running on PR without any reviews should fail
  pull_request:
  # Running on PR with the proper approving reviewer should pass
  pull_request_review:

defaults:
  run:
    shell: bash

permissions:
  # read contents of repo; all other permissions default to `none`
  contents: read

# This allows a subsequently queued workflow run to interrupt/cancel previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id}}
  cancel-in-progress: true

env:
  PR_NUMBER: ${{ github.event.number || github.event.pull_request.number }}

jobs:
  pr-review-check:
    runs-on: ubuntu-latest
    steps:
      # TODO: Find the required reviewer (not the author) for the PR
      - uses: octokit/request-action@v2.3.1
        id: get_reviews
        with:
          route: GET /repos/{owner}/{repo}/pulls/${{ env.PR_NUMBER }}/reviews
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo reviews: '${{ steps.get_reviews.outputs.data }}'"
      # TODO: Check if the required reviewer has approved the PR
